### PR TITLE
Translate of module Resources

### PR DESCRIPTION
**Pull request by Cesarfr**
* This patches adds selectable languages to the Resources module.
* Fixed stylesheets.
* All visible strings in the files PHP were translated also the JavaScript strings.
* Changed charset 'latin1' to 'utf8' in the database to future news languages.
* All updates are merged in this repository to add the new features (v1.3).
* Added script to change the database charset to utf8 in an existing installation.

Now you can change the language of the interfaces dynamically thanks to the dropdown added in all interfaces, in this update English is the language for default, but you can change the language to French if you prefer.
The dropdown is in the right of the screen, next to the dropdown to change the module:
selection_013

## Screenshots
This module should look as follows:

### Home
**English**
res_home-en

**French**
res_home-fr

### New resource
**English**
res_addr-en

**French**
res_addr-fr

### Import
**English**
res_imp-en
res_impf-en

**French**
res_imp-fr
res_impf-fr

### Admin
**English**
res_admin_en

**French**
res_admin-fr

### JavaScript
This is an example of translate in the JavaScript functions:
**English**
res_js-en

**French**
res_js-fr

To know more about what translation and internationalization are and how they work, see this page on the wiki: [Translation of ERMS CORAL](https://github.com/ndlibersa/CORAL-Main/wiki/Translation-of-ERMS-CORAL).

### CODE REVIEW

**Comment by remocrevo** [comment]
This probably needs an upgrade script also, to allow current CORAL installations to upgrade from Latin1 database tables to UTF-8. The upgrade script should be careful to convert any special characters so they are properly encoded after the upgrade.

**Comment by Cesarfr** [comment]
Hello @remocrevo I fixed the problem to add new languages and added script SQL to change the charset to UTF8

**Comment by coraladmin** [comment]
@remocrevo , are you satisfied that the concerns you raised have been met?

**Comment by PaulPoulain** [comment]
This pull request can be closed (I don't think I can. Or you'll have to explain how...), it's replaced by the #49 (sorry, I'm not completely fluent with some github features...)

**Pull request closed without merging**
