### PR TITLE
Resources description

### PR DESCRIPTION
**Pull request by veggiematts**
- Adds the ability to specify if a resource is mandatory.

This patch does not include database update, as I'm not sure what the workflow for updates is. Fresh install SQL file has been modified though.

### CODE REVIEW

**Comment by remocrevo** [comment]
@PaulPoulain or @veggiematts , have you talked to your customer libraries about the options mentioned above (using acquisition type of "Mandatory", or setting optional journals as children of the related mandatory one)?  If you decide that this new feature is necessary to meet their needs, I think the "mandatory" dropdown should instead be a checkbox, and the search field should be changed accordingly (possibly to say "Limit to mandatory?" with a checkbox, or something like that).

**Comment by benheet** [comment]
We had some discussion about this a while back over email. The last email from me was the following...

"This sounds like a valid use case and I can see how the acquisition type would not be the preferred mechanism for doing this. I do however still believe that the field should be altered so that it allows for other use cases. The label 'Mandatory' with field values of No/Yes makes this a very limited feature. I still believe that changing the field to a label such as 'Flags' and then allowing more potential values makes the most sense. In this case for Lyons 1 the potential value could be Mandatory. Other values could be Mandatory - Yes or Mandatory - No but I think Mandatory - No would be assumed making the only necessary value Mandatory. This would allow the same type of tracking and reporting options that Lyons 1 presents in their use case but then also allows the field to function for other purposes and other use cases that may come up in the future. Hopefully this is an acceptable compromise. I do wish to see this new field included to allow coral to be a better tool for Lyons 1 and other libraries in France. "

Through the email discussion it made sense to me that the Acq Type field was not the right place to do this. My suggestion was a proposed compromised that would allow for the new field but also leave it open for other use cases in the future so that we could avoid adding new data elements for other types of flags or title qualities that end up having value down the road.

Paul P., did you take the proposed suggestion back to Lyon 1 and see if they would accept this type of flag field in order to have the same functionality as a compromise?

**Comment by veggiematts** [comment]
Lyon 1 will use the note field to keep track of which resource is mandatory. I think we can close this pull request as it is too specific for being merged. Another one could be opened if someone decide to make a more generic implementation of the flags.

**Comment by benheet** [comment]
@veggiematts Thank you for the update. I appreciate your willingness to work together toward a compromise. I agree that it makes sense to revisit when there are more use cases for the flag feature. I will close the pull request.

**Pull request closed without merging**
