### PR TITLE
Correct broken mysql_query

### PR DESCRIPTION
**Pull request by jamesrf**
When I try to install this module, I am getting the error "Fatal error: Call to undefined function mysql_query() in /var/www/html/resources/install/install.php on line 64"

I suspect this was broken by 26ae17cbbc7a9b0d65786d7bd40dc6f61605c015 which changes a lot of mysql_query calls, and also the commit message says "not yet tested"

### CODE REVIEW

**Comment by remocrevo** [comment]
@jamesrf What version of mysql are you running?

**Comment by remocrevo** [comment]
@jamesrf And what version of php?

**Comment by jeffnm** [comment]
@remocrevo It looks like a mysql_query() call was not updated to the mysqli equivalent in the install.php file when the rest of the code was updated. 

This may be a bug fix we merge in despite the code freeze.

**Comment by jamesrf** [comment]
Hey, sorry I'm new to the community and was not aware there was a code freeze.  

I am using MySQL 5.7.11 and PHP 5.6.18 (specifically the versions here: https://hub.docker.com/_/php/ and https://hub.docker.com/_/mysql/).

**Comment by jeffnm** [comment]
@jamesrf No worries! We appreciate your involvement. 

Regarding the code freeze, we are moving to a single repository model for CORAL and are trying to time the merge carefully. It shouldn't stop us from applying fixes like this, although once the merge is complete we'll have to duplicate them on the new repository. In any case, thanks again for your contribution.

**Comment by PaulPoulain** [comment]
We are in the process of moving to a merged repository for all modules. I've ported your patch here : https://github.com/Coral-erm/Coral/pull/1
I suggest you close this PR.

**Comment by coraladmin** [comment]
I tried to test PR71 [resources]  with the merged repo, but the web 
installer complains about missing admin/configuration.ini. I can't see 
PR71 also supposed to address this issue besides its original purpose. 
Did I miss any thing or some changes in the installation steps?  By the 
way, should i append this comment directly into the PR 71's comments or 
still send it here?

Mang

**Pull request closed without merging**
