### PR TITLE
Translation of resource module

### PR DESCRIPTION
**Pull request by PaulPoulain**
I've tested & improved the translation to french of Resource module.

Could not find any error, we can merge this branch

### CODE REVIEW

**Comment by coraladmin** [comment]
How does this relate to pull request #42 opened by Cesar?

**Comment by Cesarfr** [comment]
Hello @coraladmin  , the difference between my pull request is the translation of all strings, because I'm not French and there are some errors in the French syntax.

**Comment by benheet** [comment]
the closed pull request #42 dealt with the need for an update script to upgrade current installations from latin1 database tables to utf-8. Does this pull request include the same or has that been dealt with somewhere else?

**Comment by Cesarfr** [comment]
Hello @benheet , the script to change the charset (**latin1** to **utf8**) in a current installation is included in this pull request also in the closed pull request (#42), the script is named `update_latin1-to-utf8.sql` . Also there is a manual to use this script (`manual_upgrade_charset_utf8.txt`).

Thanks.

**Comment by benheet** [comment]
Thank you @Cesarfr I am glad to hear that it is included.

**Pull request closed without merging**
